### ISSUE TITLE
Keybase.md proof

### ISSUE THREAD

**Issue by Crypt05haman** [keybase/proofs#159]
{
  "body": {
    "device": {
      "id": "1f030f3a6efdf7b32ae97beca6cadb18",
      "kid": "0120366af671461471dfc1809052146e7e4eabc68e4aed06e016de92b6f697654ab20a",
      "name": "FREEDOM",
      "status": 1,
      "type": "desktop"
    },
    "key": {
      "host": "keybase.io",
      "kid": "0120366af671461471dfc1809052146e7e4eabc68e4aed06e016de92b6f697654ab20a",
      "uid": "fd54aee4d76a42273f46e03252f5ae19",
      "username": "den_freeman"
    },
    "merkle_root": {
      "ctime": 1568524157,
      "hash": "d539de15963689cb98bb6e9523ea5eaac2fc7b8db0f26914749f19246a4e22458684c223a146e523f47a7ea2361ea9bd252b86ccb553ddf58d4ec5624dafd67c",
      "hash_meta": "bdd52bed4a9f0de9b976abaa90666fe96f793d1d02c4841c3749d8e6065a4b76",
      "seqno": 7370096
    },
    "type": "eldest",
    "version": 1
  },
  "client": {
    "name": "keybase.io go client",
    "version": "4.4.2"
  },
  "ctime": 1568524159,
  "expire_in": 504576000,
  "prev": null,
  "seqno": 1,
  "tag": "signature"
}

**Comment by hexandcube** [comment]
@Crypt05haman This is not a place for Keybase Proofs. You should post it as a gist on [gist.github.com](https://gist.github.com). **Please close this issue**.
