### ISSUE TITLE
Simplify Reddit Scraping strategy

### ISSUE THREAD

**Issue by maxtaco** [keybase/proofs#25]
Right now we're scraping from keybase-proofs subreddit, but it might be easier to scrape on the per-user page.  In v2.0.26, we pushed some temporary bugfixes to crashers, but we should do the right thing and fix and simplify our strategy.

**Comment by Sidnicious** [comment]
:sparkles: a471ca8088ffaa8d4991b209181cbc7ae5b84488 :sparkles:

**Comment by maxtaco** [comment]
:+1:
