### ISSUE TITLE
API network error facebook

### ISSUE THREAD

**Issue by paulhugel** [keybase/proofs#60]
keybase id --skip-proof-cache
▶ INFO Identifying paulhugel
✔ public key fingerprint: D922 B7B1 3A4D 9BF9 0927 DCA1 7A14 4B7D A3F4 8305
฿  bitcoin 1KbKNUaZFwF7s9j3UNLaPycPvYgoSqwuFW
✔ admin of DNS zone nko.org: found TXT entry keybase-site-verification=lCQtHEPPWQAyyAZLOxbIeUQxdYO4EIIxqo_vswfRsB8
✔ "paulhugel" on github: https://gist.github.com/8e3ae3921cc2e7c89e0d
✔ "paulhugel" on hackernews: https://news.ycombinator.com/user?id=paulhugel
✔ admin of paulhugel.keybase.pub via HTTPS: https://paulhugel.keybase.pub/keybase.txt
✔ "paulhugel" on twitter: https://twitter.com/paulhugel/status/588158776471003136
✔ "paulhugel" on reddit: https://www.reddit.com/r/KeybaseProofs/comments/32n9ej/my_keybase_proof_redditpaulhugel_keybasepaulhugel/
✔ admin of nko.org via HTTPS: https://nko.org/keybase.txt
✔ "paulghugel" on facebook failed: API network error: Get https://www.facebook.com/paulghugel/posts/698602107008518: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) (code=170)
Pauls-MacBook-Air:~ paul$ 
Pauls-MacBook-Air:~ paul$ 
Pauls-MacBook-Air:~ paul$ keybase version
Client:  1.0.21-20170413194757+9dea6e1
Service: 1.0.21-20170413194757+9dea6e1

**Comment by cjb** [comment]
It looks like your network connection to Facebook is failing?  Like maybe it's firewalled off or there's some kind of outage.

**Comment by paulhugel** [comment]
Today I re-ran the command but Keybase app still shows "UNREACHABLE

:~ paul$ keybase id --skip-proof-cache
▶ INFO Identifying paulhugel
✔ public key fingerprint: D922 B7B1 3A4D 9BF9 0927 DCA1 7A14 4B7D A3F4 8305
฿  bitcoin 1KbKNUaZFwF7s9j3UNLaPycPvYgoSqwuFW
✔ admin of DNS zone nko.org: found TXT entry keybase-site-verification=lCQtHEPPWQAyyAZLOxbIeUQxdYO4EIIxqo_vswfRsB8
✔ "paulhugel" on github: https://gist.github.com/8e3ae3921cc2e7c89e0d
✔ "paulhugel" on reddit: https://www.reddit.com/r/KeybaseProofs/comments/32n9ej/my_keybase_proof_redditpaulhugel_keybasepaulhugel/
✔ "paulghugel" on facebook: https://facebook.com/620211084847621_698602107008518
✔ "paulhugel" on twitter: https://twitter.com/paulhugel/status/588158776471003136
✔ admin of nko.org via HTTPS: https://nko.org/keybase.txt
✔ "paulhugel" on hackernews: https://news.ycombinator.com/user?id=paulhugel
✔ admin of paulhugel.keybase.pub via HTTPS: https://paulhugel.keybase.pub/keybase.txt
Pauls-MacBook-Air:~ paul$ 
![screen shot 2017-04-25 at 5 38 55 pm](https://cloud.githubusercontent.com/assets/6466830/25417187/1853deec-29de-11e7-89df-01ea10e12822.png)

**Comment by paulhugel** [comment]
just ran command second time 

Pauls-MacBook-Air:~ paul$ keybase id --skip-proof-cache
▶ INFO Identifying paulhugel
✔ public key fingerprint: D922 B7B1 3A4D 9BF9 0927 DCA1 7A14 4B7D A3F4 8305
฿  bitcoin 1KbKNUaZFwF7s9j3UNLaPycPvYgoSqwuFW
✔ "paulhugel" on twitter: https://twitter.com/paulhugel/status/588158776471003136
✔ "paulhugel" on reddit: https://www.reddit.com/r/KeybaseProofs/comments/32n9ej/my_keybase_proof_redditpaulhugel_keybasepaulhugel/
✔ admin of DNS zone nko.org: found TXT entry keybase-site-verification=lCQtHEPPWQAyyAZLOxbIeUQxdYO4EIIxqo_vswfRsB8
✔ "paulhugel" on github: https://gist.github.com/8e3ae3921cc2e7c89e0d
✔ admin of nko.org via HTTPS: https://nko.org/keybase.txt
✔ "paulhugel" on hackernews: https://news.ycombinator.com/user?id=paulhugel
✔ admin of paulhugel.keybase.pub via HTTPS: https://paulhugel.keybase.pub/keybase.txt
✔ "paulghugel" on facebook failed: API network error: Get https://www.facebook.com/paulghugel/posts/698602107008518: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) (code=170)
Pauls-MacBook-Air:~ paul$

**Comment by paulhugel** [comment]
Facebook looking normal again?
![screen shot 2017-04-25 at 5 47 52 pm](https://cloud.githubusercontent.com/assets/6466830/25417399/863e290c-29df-11e7-82b2-5d5b27240405.png)

**Comment by paulhugel** [comment]
still getting intermittent

"paulghugel" on facebook failed: API network error: Get https://www.facebook.com/paulghugel/posts/698602107008518: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) (code=170)
