### ISSUE TITLE
Flickr QR Code

### ISSUE THREAD

**Issue by pathawks** [keybase/proofs#7]
To prove a Flickr identity (or other photo sharing services), could the signed JSON be encoded into a QR code image, or is that too tricky?

**Comment by kirelagin** [comment]
I’m not an active flickr user, but I’m pretty sure it has photo descriptions.
So posting a random picture (or not random, but the Keybase logo) with an appropriate description should be enough.

**Comment by pathawks** [comment]
@kirelagin Photo descriptions can change at any time. Reuploading a photo will break the old URL.

**Comment by kirelagin** [comment]
> Photo descriptions can change at any time.

So what?

**Comment by pathawks** [comment]
> So what?

Same reason that Twitter authentication is done via tweet rather than in the bio.

**Comment by kirelagin** [comment]
I guess the reason why Twitter verification is not done in bio is that bio is typically reserved for something short and meaningful and always stays on top so the place there is somewhat expansive it terms of usefulness. But purely _technically_ there is nothing wrong with doing this in the twitter bio.

Comment of a photo in the flickr photostream is pretty much the same as a tweet in the twitter timeline. So posting the verification text in a comment of a (random) picture seems to be the most straightforward and convenient way. BTW space on the Flickr “Profile” page is way less expansive than bio in Twitter, so posting the verification text there also does make sense.

**Comment by pathawks** [comment]
> But purely technically there is nothing wrong with doing this in the twitter bio.

This has been discussed before elsewhere, but there *is* a technical reason why this is not done.

Somebody can change their bio at anytime, but cannot modify a tweet once it has been posted.
If you verified with a Tweet a year ago, and that verification is still valid, I can know that nobody changed your key last night. If you verified with something like a bio, I have no way of knowing that.

**Comment by kirelagin** [comment]
> If you verified with a Tweet a year ago, and that verification is still valid, I can know that nobody changed your key last night.

Now, this does make sense.

Well, actually, there is a better way to know whether someone has changed my key last night: keep the “key changed” records in the signature chain and make clients output the last changed date.

**Comment by oconnor663** [comment]
The user's signature chain does contain the date when all their proofs were first posted, so the most solid way to check the date of a proof is to look at that. You can crossreference Keybase's merkle roots with the bitcoin blockchain to be sure we're not lying. This isn't automated yet in any convenient way that I know of, but it does mean that we don't need to rely on trusting Twitter and other providers to date a proof.

**Comment by mralext20** [comment]
im sorry this is a year in the past, but you can also edit GH gists. so there's no reason why you cant have the message be editable.

**Comment by zhuowei** [comment]
@mralext20 I believe the gist fetcher keeps the Git commit hash in the url, ensuring that only that particular revision would be fetched and displayed.

**Comment by dragon788** [comment]
Because of the extra checksumming available in a QR code you can "degrade" the image by inserting an additional image into the center and still leave it a valid QR code. Is there some other piece of information that could be encoded that would be visual and allow a user to easily see who the QR code claims to be from, maybe an overlaid block of letters from a hash of the fingerprint?

http://stackoverflow.com/questions/3339202/how-to-create-qr-code-image-with-company-logo
http://twainscanning.com/how-to-customize-qr-code-add-a-logo-to-it/
