### ISSUE TITLE
Web proof for https://www.owlfolio.org/ not working, server won't retry

### ISSUE THREAD

**Issue by zackw** [keybase/proofs#70]
The Keybase server claims not to be able to verify the proof for https://www.owlfolio.org/ since May 16.  Nothing has changed on my site, and I can manually verify (with a web browser) that https://www.owlfolio.org/.well-known/keybase.txt still exists and its contents are unchanged since I put it there quite some time ago.  When I tell the Keybase server to retry the proof, it _immediately_ tells me that the proof still fails.  The access logs for my site indicate that keybase-proofs/2.1.11 has not even tried to download the proof since May 16.  What might be wrong?

**Comment by zackw** [comment]
(To be clear, from my end, it appears that the keybase server _doesn't_ try to access the proof even when told to with the web UI.)

**Comment by oconnor663** [comment]
I notice that when I try to `curl` your proof, I get a gzip encoded version. It might be that your webserver is sending gzip without checking the Accept-Encoding header? I'm not familiar enough with that header to know any more than that though. 

P.S. Let's Encrypt was down today, though I think that would only have affected you if you were trying to renew?

**Comment by zackw** [comment]
I was going to say that I don't think that can be the problem, because that would still get to the point where my webserver shows an access log entry for the keybase proof-checker... except that I don't see an access log entry for your curl test, either.  Other stuff is getting logged though.  Weird.

**Comment by oconnor663** [comment]
Interesting. I ran a few different `-v` variants of `curl https://www.owlfolio.org/.well-known/keybase.txt`.

**Comment by zackw** [comment]
On further investigation, the access logs are a red herring, and you're absolutely right that it was sending gzipped content when it shouldn't.  I have fixed the site configuration, but due to the somewhat Rube Goldberg hosting arrangement I have, it may take a while for that to take effect (there's a reverse proxy that I don't directly control, that has cached stuff incorrectly, and I don't know how long it will be stuck that way).

However, shouldn't the proof-checker accept gzipped content (and say so in Accept-Encoding)?

**Comment by zackw** [comment]
The bad cached data timed out and the keybase server now accepts my proof again.

Can we morph this into a feature request for the keybase web UI to give more helpful error messages when a proof fails?  We could have avoided all this if it had given any indication of what the problem was.

**Comment by oconnor663** [comment]
Agreed that this sort of thing tends to be super mysterious, and apologies for the goose chase. There are a couple difficulties in building meaningful error reporting into the proof checker, unfortunately: 1) Checking is usually asynchronous, 2) Most error messages are gobbledygook to most users ("HTTP error code such-and such", "div #so-and-so missing", etc). We could build around all these problems, but it would take enough effort to do a good job that it probably won't get priority for a while.

**Comment by zackw** [comment]
Understood.

**Comment by BenjaminHCCarr** [comment]
Can we close this one?
It was solved, which is good for those trying to work on proofs, but as it was solved should be closed.
