### ISSUE TITLE
Spotify proof support

### ISSUE THREAD

**Issue by xkr47** [keybase/proofs#78]
In Spotify one could create a public playlist named "Keybase" and add the proof (300 chars max) in the description field, which could then be verified directly from the web..
(moved from keybase/client#5974)

**Comment by mittalyashu** [comment]
There are still few countries which Spotify doesn't support.

**Comment by xkr47** [comment]
Am I correct that you mean a Spotify proof is not currently interesting as it wouldn't be universally verifiable?

**Comment by xkr47** [comment]
Very well, thanks!
