### ISSUE TITLE
Migrate proofs to PGP key

### ISSUE THREAD

**Issue by Gunni** [keybase/proofs#84]
Hey, i have this graph:

![gg-1510052297](https://user-images.githubusercontent.com/358099/32490428-1748299c-c3ab-11e7-8a15-5021433fc6d1.png)

I want to perform the changes marked in red.

How can these changes be done, and where is the interface for this documented?

**Comment by gappleto97** [comment]
Is it possible to change the connections at all? I did not think it was.

**Comment by Gunni** [comment]
@gappleto97 yes by making a new connection?

**Comment by gappleto97** [comment]
I mean, yes, but I dont think there is any documented way to add connections without adding devices/keys

**Comment by Gunni** [comment]
@gappleto97 yes, and therefore this issue exists
